version: '3' 

services:
    
  web: 
    build: ./docker-config/php
    container_name: app_php
    volumes:
      - ./src:/var/www/src
    working_dir: /var/www/src
    depends_on:
      - mysql

  nginx:
    image: nginx
    container_name: app_nginx
    build: ./docker-config/nginx
    ports:
      - "81:80"
    volumes:
      - ./src:/var/www/src
      - ./docker-config/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web

  mysql:
    image: mysql:8.0
    container_name: app_db
    ports:
      - 3316:3306
    environment:
      MYSQL_DATABASE: development
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: m_user
      MYSQL_PASSWORD: m_user
      TZ: 'Asia/Tokyo'
      
    volumes:
      - ./docker-config/mysql/data:/var/lib/mysql
      - ./docker-config/mysql/my.cnf:/etc/mysql/conf.d/my.cnf

    depends_on:
      - mysql-volume

  mysql-volume:
    image: busybox
    volumes:
      - ./docker-config/mysql/data:/var/lib/mysql

